---
kind: pipeline
name: acceptance-tests

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - pull_request
    - push
  branch:
    exclude:
      - master

steps:
- name: build and vet the provider
  pull: always
  image: golang:1.15
  commands:
    - make
  environment:
    GO111MODULE: on

- name: run acceptance tests
  pull: always
  image: golang:1.15
  commands:
    - apt-get update && apt-get install unzip -y
    - wget https://releases.hashicorp.com/terraform/$${TF_VERSION}/terraform_$${TF_VERSION}_linux_amd64.zip
    - unzip terraform_$${TF_VERSION}_linux_amd64.zip
    - mv terraform /usr/bin/terraform
    - sleep 30
    - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  environment:
    TF_ACC: 1
    TF_VERSION: 0.14.3
    GO111MODULE: on
    SONAR_HOST: http://sonarqube:9000
    SONAR_USER: admin
    SONAR_PASS: admin

services:
- name: sonarqube
  pull: default
  image: sonarqube:latest

---
kind: pipeline
name: master

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - pull_request
    - push
  branch:
    - master

steps:
- name: build and vet the provider
  pull: always
  image: golang:1.15
  commands:
    - make
  environment:
    GO111MODULE: on

- name: run acceptance tests
  pull: always
  image: golang:1.15
  commands:
    - apt-get update && apt-get install unzip -y
    - wget https://releases.hashicorp.com/terraform/$${TF_VERSION}/terraform_$${TF_VERSION}_linux_amd64.zip
    - unzip terraform_$${TF_VERSION}_linux_amd64.zip
    - mv terraform /usr/bin/terraform
    - sleep 30
    - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  environment:
    TF_ACC: 1
    TF_VERSION: 0.14.3
    GO111MODULE: on
    SONAR_HOST: http://sonarqube:9000
    SONAR_USER: admin
    SONAR_PASS: admin

- name: coverage
  image: plugins/codecov
  settings:
    token: 
      from_secret: codecov_token
    files:
     - coverage.txt
  when:
    event:
      - push
    branch:
      - master

services:
- name: sonarqube
  pull: default
  image: sonarqube:latest